### ISSUE TITLE
how to access GEE assets: projects/global-flood-db/dfo-polygons/

### ISSUE THREAD

**Issue by sbaber1** [cloudtostreet/MODIS_GlobalFloodDatabase#2]
Noticed that there are DFO shapefiles in the 'data' folder, but does not contain the 'ThreshType' column that feeds into 'main_gfd.py'

**Comment by LeeYayi** [comment]
Hi, sbaber1

I have this problem too, may I ask you how you solved this?

big thx

**Comment by sbaber1** [comment]
Instead of deriving the threshold from the DFO shapefiles, I hardcoded the threshold (`thresh_type = 'std'` ) or (`thresh_type = 'otsu')` in the main_gfd.py file. Hope that is helpful!

**Comment by LeeYayi** [comment]
> Instead of deriving the threshold from the DFO shapefiles, I hardcoded the threshold (`thresh_type = 'std'` ) or (`thresh_type = 'otsu')` in the main_gfd.py file. Hope that is helpful!

thanks a lot, you r so nice😉
